### ISSUE TITLE
Benefits over GradientDrawable

### ISSUE THREAD

**Issue by consp1racy** [csdodd/GradientLayout#1]
Hello, could you describe benefits of using this library over using a XML gradient drawable? Thank you.

**Comment by csdodd** [comment]
There are no major benefits to this library -- in fact an XML gradient drawable will give you much more flexibility whereas this library is just a simple wrapper around GradientDrawable.

It has the advantage of generating and rendering a gradient for you even if you only provide it with one color. It is also arguably easier to work with if you need to dynamically create a lot of gradients.

Take the case of a messaging app; you may for example want to render a different color gradient for each contact - this allows you to easily do that.

**Comment by csdodd** [comment]
I have just tweaked the library slightly to make this more obvious - and I have included an example in the README.

If you only supply a `startColor` or an `endColor` to the library then it will take care of generating a gradient.
